-- Table: public.cart

-- DROP TABLE IF EXISTS public.cart;

CREATE TABLE IF NOT EXISTS public.cart
(
    cartid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    productid integer NOT NULL,
    quantity integer NOT NULL,
    createdby integer,
    createdon timestamp without time zone,
    modifiedby integer,
    modifiedon timestamp without time zone,
    isactive boolean,
    isdeleted boolean,
    CONSTRAINT cart_pkey PRIMARY KEY (cartid),
    CONSTRAINT fk_productid FOREIGN KEY (productid)
        REFERENCES public.products (productid) 
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cart
    OWNER to postgres;