-- Table: public.order

-- DROP TABLE IF EXISTS public."order";

CREATE TABLE IF NOT EXISTS public."order"
(
    orderid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1),
    productid integer NOT NULL,
    quantitiy integer NOT NULL,
    productprice numeric NOT NULL,
    overallprice numeric NOT NULL,
    createdby integer,
    createdon timestamp without time zone,
    modifiedby integer,
    modifiedon timestamp without time zone,
    isactive boolean,
    isdeleted boolean,
    CONSTRAINT order_pkey PRIMARY KEY (orderid),
    CONSTRAINT fk_productid FOREIGN KEY (productid)
        REFERENCES public.products (productid)
)
