-- Table: public.products

-- DROP TABLE IF EXISTS public.products;

CREATE TABLE IF NOT EXISTS public.products
(
    productid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    productname character varying(255) NOT NULL,
    description text,
    originalprice numeric(18,2) NOT NULL,
    offerprice numeric(18,2),
    stockquantity integer NOT NULL,
    subcategoryid integer,
    isactive boolean,
    isdeleted boolean,
    createdby integer,
    createdon timestamp with time zone,
    modifiedby integer,
    modifiedon timestamp with time zone,
    CONSTRAINT products_pkey PRIMARY KEY (productid),
    CONSTRAINT fk_subcategoryid FOREIGN KEY (subcategoryid)
        REFERENCES public.subcategory (subcategoryid) 
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.products
    OWNER to postgres;