-- Table: public.subcategory

-- DROP TABLE IF EXISTS public.subcategory;

CREATE TABLE IF NOT EXISTS public.subcategory
(
    subcategoryid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1),
    subcategoryname character varying(50),
    categoryid integer,
    isactive boolean,
    isdeleted boolean,
    createdby integer,
    createdon timestamp with time zone,
    modifiedby integer,
    modifiedon timestamp with time zone,
    CONSTRAINT subcategory_pkey PRIMARY KEY (subcategoryid),
    CONSTRAINT fk_categoryid FOREIGN KEY (categoryid)
        REFERENCES public.category (categoryid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.subcategory
    OWNER to postgres;