-- Table: public.userdetail

-- DROP TABLE IF EXISTS public.userdetail;

CREATE TABLE IF NOT EXISTS public.userdetail
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1),
    userid integer,
    isloggedin boolean,
    otp text,
    createdby integer,
    createdon timestamp with time zone,
    modifiedby integer,
    modifiedon timestamp with time zone,
    isdeleted boolean,
    CONSTRAINT userdetail_pkey PRIMARY KEY (id),
    CONSTRAINT fk_userid FOREIGN KEY (userid)
        REFERENCES public.users (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.userdetail
    OWNER to postgres;